// Auto-generated TypeScript types from database schema
// DO NOT EDIT MANUALLY - This file is generated by generate_database_types tool

export interface DownloadRecordsRow {
  id: number;
  corp_id: string | null;
  emp_id: string;
  drawing_id: number;
  download_time: string | null;
  ip_address: string | null;
  user_agent: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type DownloadRecordsInsert = Omit<DownloadRecordsRow, 'id' | 'corp_id' | 'emp_id' | 'download_time' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type DownloadRecordsUpdate = Partial<DownloadRecordsInsert>;

export interface DrawingCategoriesRow {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  name: string;
  code: string | null;
  parent_id: number | null;
  sort_order: number | null;
  description: string | null;
  drawing_count: number | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type DrawingCategoriesInsert = Omit<DrawingCategoriesRow, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type DrawingCategoriesUpdate = Partial<DrawingCategoriesInsert>;

export interface DrawingVersionsRow {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  drawing_id: number;
  version: string;
  file_path: string;
  file_name: string;
  file_size: number | null;
  change_description: string | null;
  is_current: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type DrawingVersionsInsert = Omit<DrawingVersionsRow, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type DrawingVersionsUpdate = Partial<DrawingVersionsInsert>;

export interface DrawingsRow {
  id: number;
  corp_id: string | null;
  emp_id: string | null;
  name: string;
  code: string | null;
  category_id: number | null;
  file_path: string;
  file_name: string;
  file_size: number | null;
  file_format: string | null;
  version: string | null;
  status: string | null;
  description: string | null;
  download_count: number | null;
  thumbnail_path: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type DrawingsInsert = Omit<DrawingsRow, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type DrawingsUpdate = Partial<DrawingsInsert>;
